Change QR code generator from google to quickchart.io
jetrails/magento-twofactor pull request #28
Opened 2024-10-09 20:37 UTC by marcogruhl

As of april 2024 charts.google.com dont generate QR codes anymore so i changed it to quickchart.io

2024-10-10 15:16 UTC, null93 requested changes
Thank you for contributing back to the project! I'd like to suggest that we set the margin to 1 as well.

Are you able to test these changes out once I release a new version?

2024-10-10 15:16 UTC, null93 commented on src/app/code/community/JetRails/TwoFactor/Helper/Totp.php
> +			$url .= "&width=" . $size . "&height=" . $size;
```suggestion
			$url .= "&width=" . $size . "&height=" . $size;
			$url .= "&margin=1";
```

2024-10-10 20:30 UTC, marcogruhl commented
> Thank you for contributing back to the project! I'd like to suggest that we set the margin to 1 as well.
> 
> Are you able to test these changes out once I release a new version?

I am able to "test" it. I will use it in our live online store, i also implemented the new QR code generator manually and it works.

2024-10-11 17:39 UTC, null93 approved these changes
Thank you!!

2024-10-11 17:39 UTC, merged

2024-10-11 22:43 UTC, marcogruhl commented
Thank you for accepting the PR! 
FYI: I use it in an OpenMage 2.10. Store and enrolled it for me and it works. Will enroll it for all in the next days.
PS: if i find more i will make a new PR
PPS: Maybe you can remove the links to the (not working) MagentoMarketplace?

2024-10-12 00:05 UTC, null93 commented
Fantastic! Definitely let me know if you find something else. PRs always welcome.

I removed the link and also added an entry to COMPATIBILITY.md.